languageCode = "en"
defaultContentLanguage = "en"

title = "Valorant Match Schedule 📅"
copyright = "© 2023 miztch | <a class='hover:underline hover:decoration-primary-400 hover:text-primary-500' href='https://github.com/miztch/valorant-match-schedule'>GitHub</a>"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

googleAnalytics = "G-T160DKFZWX"

[author]
  headline = "Check Valorant competitive match schedule on Google Calendar!"

  links = [
    { international = { href = "https://calendar.google.com/calendar/u/0?cid=ZjJiMjY1MTkwZmNkMDY5NjY5M2FiZjgwODE1OGRkZDQ1MTQwNjY1ZGRkMGM1YjM3YWFhYTA0ZGJjZDYxZWFhOEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "International" }},
    { emea = { href = "https://calendar.google.com/calendar/u/0?cid=OWNjOGI0YmIwMjFiMDE5NGIyNDEzOWRiMjU1NjFmYTc0ZGVhYTc0MzU0YWY1NDkzMDFiNDRhZWNjOTJiMzJiOUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "EMEA" }},
    { na = { href = "https://calendar.google.com/calendar/u/0?cid=NDg2OTg5YjJjYTEwZTk5OGVlODU4YTcyMDRiMTNjZDkzNWQ0MTFmMjlkYzA4MzA1ZGJiZDFjNDIzN2YyYTIxZEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "North America" }},
    { br-latam = { href = "https://calendar.google.com/calendar/u/0?cid=NTNjYTg1NDZhNGQzM2IzMTkzNmVkMjA0NjE2NmY2OTA2ODc1YzhiMzM3N2JhOThiOWFkMWJhZjNhMDQwZjA3NUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "BR / LATAM" }},
    { apac = { href = "https://calendar.google.com/calendar/u/0?cid=YTZiOWM3ZGI5YzdmM2U2YjFmNjNmMjc4MjhkMzM0ZjQ0NTFhZDI0ZGU1NzA0YjI4YTk5YzU1ZGEwNjk5YjdiZkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "APAC" }},
    { east-asia = { href = "https://calendar.google.com/calendar/u/0?cid=MWEyMWYzYWFlMDRjYWJiODQxNDFlOGE1ZjRhYTRjZTA4NWNmMzZlNDA0YjQyOGIzYjZjNzYxMWE4MTllZjczMkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t", text = "East Asia" }}
  ]

[params]
  description = 'Check Valorant competitive match schedule on Google Calendar!'
  images = [ 'img/screenshot.png' ]
  title = 'Valorant Match Schedule'

[social]
  twitter = 'm1ztch'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

[markup.goldmark.renderer]
unsafe = true

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://valorant-calendar.mizt.ch?region=us-east-1"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true