on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: true
      - name: Install Hugo
        env:
          HUGO_VERSION: 0.113.0
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
      - name: Hugo Build
        run: hugo -v
      - name: Deploy to S3
        run: hugo -v deploy --maxDeletes 1000
      - name: flush CloudFront Edge Cache
        run: |
          aws cloudfront list-distributions \
          | jq -r '.DistributionList.Items[] | select(.Aliases.Items[0]=="valorant-calendar.mizt.ch" ) | .Id ' \
          | xargs -I {} aws cloudfront create-invalidation --distribution-id {} --paths "/*"
