on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Install Hugo
        env:
          HUGO_VERSION: 0.113.0
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
      - name: Hugo Build
        run: |
          cd website/
          $HOME/hugo -v
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd website/
          $HOME/hugo -v deploy --maxDeletes 1000
      - name: flush CloudFront Edge Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront list-distributions \
          | jq -r '.DistributionList.Items[] | select(.Aliases.Items[0]=="valorant-calendar.mizt.ch" ) | .Id ' \
          | xargs -I {} aws cloudfront create-invalidation --distribution-id {} --paths "/*"
